// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_ToClient.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "test_ToClient.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace test {

namespace {

const ::google::protobuf::Descriptor* ToClient_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ToClient_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ToClient_Type_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_test_5fToClient_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_test_5fToClient_2eproto() {
  protobuf_AddDesc_test_5fToClient_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "test_ToClient.proto");
  GOOGLE_CHECK(file != NULL);
  ToClient_descriptor_ = file->message_type(0);
  static const int ToClient_offsets_[11] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, datatype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, gp2y0a_left_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, gp2y0a_right_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, sen1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, hall_left_total_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, motionst_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, motiones_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, pose_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, pose_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, pose_theta_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, image_length_),
  };
  ToClient_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ToClient_descriptor_,
      ToClient::default_instance_,
      ToClient_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, _has_bits_[0]),
      -1,
      -1,
      sizeof(ToClient),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ToClient, _internal_metadata_),
      -1);
  ToClient_Type_descriptor_ = ToClient_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_test_5fToClient_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ToClient_descriptor_, &ToClient::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_test_5fToClient_2eproto() {
  delete ToClient::default_instance_;
  delete ToClient_reflection_;
}

void protobuf_AddDesc_test_5fToClient_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_test_5fToClient_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023test_ToClient.proto\022\004test\"\224\002\n\010ToClient"
    "\022%\n\010DataType\030\001 \002(\0162\023.test.ToClient.Type\022"
    "\023\n\013GP2Y0A_Left\030\002 \002(\r\022\024\n\014GP2Y0A_Right\030\003 \002"
    "(\r\022\014\n\004SEN1\030\004 \002(\r\022\027\n\017Hall_Left_Total\030\005 \002("
    "\005\022\020\n\010MotionSt\030\006 \002(\r\022\020\n\010MotionEs\030\007 \002(\r\022\016\n"
    "\006pose_x\030\010 \002(\002\022\016\n\006pose_y\030\t \002(\002\022\022\n\npose_th"
    "eta\030\n \002(\002\022\024\n\014Image_Length\030\013 \001(\r\"!\n\004Type\022"
    "\013\n\007NoImage\020\000\022\014\n\010HasImage\020\001", 306);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "test_ToClient.proto", &protobuf_RegisterTypes);
  ToClient::default_instance_ = new ToClient();
  ToClient::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_test_5fToClient_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_test_5fToClient_2eproto {
  StaticDescriptorInitializer_test_5fToClient_2eproto() {
    protobuf_AddDesc_test_5fToClient_2eproto();
  }
} static_descriptor_initializer_test_5fToClient_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* ToClient_Type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ToClient_Type_descriptor_;
}
bool ToClient_Type_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const ToClient_Type ToClient::NoImage;
const ToClient_Type ToClient::HasImage;
const ToClient_Type ToClient::Type_MIN;
const ToClient_Type ToClient::Type_MAX;
const int ToClient::Type_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ToClient::kDataTypeFieldNumber;
const int ToClient::kGP2Y0ALeftFieldNumber;
const int ToClient::kGP2Y0ARightFieldNumber;
const int ToClient::kSEN1FieldNumber;
const int ToClient::kHallLeftTotalFieldNumber;
const int ToClient::kMotionStFieldNumber;
const int ToClient::kMotionEsFieldNumber;
const int ToClient::kPoseXFieldNumber;
const int ToClient::kPoseYFieldNumber;
const int ToClient::kPoseThetaFieldNumber;
const int ToClient::kImageLengthFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ToClient::ToClient()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:test.ToClient)
}

void ToClient::InitAsDefaultInstance() {
}

ToClient::ToClient(const ToClient& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:test.ToClient)
}

void ToClient::SharedCtor() {
  _cached_size_ = 0;
  datatype_ = 0;
  gp2y0a_left_ = 0u;
  gp2y0a_right_ = 0u;
  sen1_ = 0u;
  hall_left_total_ = 0;
  motionst_ = 0u;
  motiones_ = 0u;
  pose_x_ = 0;
  pose_y_ = 0;
  pose_theta_ = 0;
  image_length_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ToClient::~ToClient() {
  // @@protoc_insertion_point(destructor:test.ToClient)
  SharedDtor();
}

void ToClient::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ToClient::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ToClient::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ToClient_descriptor_;
}

const ToClient& ToClient::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_test_5fToClient_2eproto();
  return *default_instance_;
}

ToClient* ToClient::default_instance_ = NULL;

ToClient* ToClient::New(::google::protobuf::Arena* arena) const {
  ToClient* n = new ToClient;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ToClient::Clear() {
// @@protoc_insertion_point(message_clear_start:test.ToClient)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(ToClient, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<ToClient*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 255u) {
    ZR_(datatype_, pose_x_);
  }
  ZR_(pose_y_, image_length_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool ToClient::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:test.ToClient)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .test.ToClient.Type DataType = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::test::ToClient_Type_IsValid(value)) {
            set_datatype(static_cast< ::test::ToClient_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_GP2Y0A_Left;
        break;
      }

      // required uint32 GP2Y0A_Left = 2;
      case 2: {
        if (tag == 16) {
         parse_GP2Y0A_Left:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &gp2y0a_left_)));
          set_has_gp2y0a_left();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_GP2Y0A_Right;
        break;
      }

      // required uint32 GP2Y0A_Right = 3;
      case 3: {
        if (tag == 24) {
         parse_GP2Y0A_Right:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &gp2y0a_right_)));
          set_has_gp2y0a_right();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_SEN1;
        break;
      }

      // required uint32 SEN1 = 4;
      case 4: {
        if (tag == 32) {
         parse_SEN1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &sen1_)));
          set_has_sen1();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_Hall_Left_Total;
        break;
      }

      // required int32 Hall_Left_Total = 5;
      case 5: {
        if (tag == 40) {
         parse_Hall_Left_Total:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &hall_left_total_)));
          set_has_hall_left_total();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_MotionSt;
        break;
      }

      // required uint32 MotionSt = 6;
      case 6: {
        if (tag == 48) {
         parse_MotionSt:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &motionst_)));
          set_has_motionst();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_MotionEs;
        break;
      }

      // required uint32 MotionEs = 7;
      case 7: {
        if (tag == 56) {
         parse_MotionEs:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &motiones_)));
          set_has_motiones();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(69)) goto parse_pose_x;
        break;
      }

      // required float pose_x = 8;
      case 8: {
        if (tag == 69) {
         parse_pose_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pose_x_)));
          set_has_pose_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(77)) goto parse_pose_y;
        break;
      }

      // required float pose_y = 9;
      case 9: {
        if (tag == 77) {
         parse_pose_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pose_y_)));
          set_has_pose_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(85)) goto parse_pose_theta;
        break;
      }

      // required float pose_theta = 10;
      case 10: {
        if (tag == 85) {
         parse_pose_theta:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &pose_theta_)));
          set_has_pose_theta();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(88)) goto parse_Image_Length;
        break;
      }

      // optional uint32 Image_Length = 11;
      case 11: {
        if (tag == 88) {
         parse_Image_Length:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &image_length_)));
          set_has_image_length();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:test.ToClient)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:test.ToClient)
  return false;
#undef DO_
}

void ToClient::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:test.ToClient)
  // required .test.ToClient.Type DataType = 1;
  if (has_datatype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->datatype(), output);
  }

  // required uint32 GP2Y0A_Left = 2;
  if (has_gp2y0a_left()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->gp2y0a_left(), output);
  }

  // required uint32 GP2Y0A_Right = 3;
  if (has_gp2y0a_right()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->gp2y0a_right(), output);
  }

  // required uint32 SEN1 = 4;
  if (has_sen1()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->sen1(), output);
  }

  // required int32 Hall_Left_Total = 5;
  if (has_hall_left_total()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->hall_left_total(), output);
  }

  // required uint32 MotionSt = 6;
  if (has_motionst()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->motionst(), output);
  }

  // required uint32 MotionEs = 7;
  if (has_motiones()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->motiones(), output);
  }

  // required float pose_x = 8;
  if (has_pose_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(8, this->pose_x(), output);
  }

  // required float pose_y = 9;
  if (has_pose_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(9, this->pose_y(), output);
  }

  // required float pose_theta = 10;
  if (has_pose_theta()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(10, this->pose_theta(), output);
  }

  // optional uint32 Image_Length = 11;
  if (has_image_length()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(11, this->image_length(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:test.ToClient)
}

::google::protobuf::uint8* ToClient::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:test.ToClient)
  // required .test.ToClient.Type DataType = 1;
  if (has_datatype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->datatype(), target);
  }

  // required uint32 GP2Y0A_Left = 2;
  if (has_gp2y0a_left()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->gp2y0a_left(), target);
  }

  // required uint32 GP2Y0A_Right = 3;
  if (has_gp2y0a_right()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->gp2y0a_right(), target);
  }

  // required uint32 SEN1 = 4;
  if (has_sen1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->sen1(), target);
  }

  // required int32 Hall_Left_Total = 5;
  if (has_hall_left_total()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->hall_left_total(), target);
  }

  // required uint32 MotionSt = 6;
  if (has_motionst()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->motionst(), target);
  }

  // required uint32 MotionEs = 7;
  if (has_motiones()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->motiones(), target);
  }

  // required float pose_x = 8;
  if (has_pose_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(8, this->pose_x(), target);
  }

  // required float pose_y = 9;
  if (has_pose_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(9, this->pose_y(), target);
  }

  // required float pose_theta = 10;
  if (has_pose_theta()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(10, this->pose_theta(), target);
  }

  // optional uint32 Image_Length = 11;
  if (has_image_length()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(11, this->image_length(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:test.ToClient)
  return target;
}

int ToClient::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:test.ToClient)
  int total_size = 0;

  if (has_datatype()) {
    // required .test.ToClient.Type DataType = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->datatype());
  }

  if (has_gp2y0a_left()) {
    // required uint32 GP2Y0A_Left = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->gp2y0a_left());
  }

  if (has_gp2y0a_right()) {
    // required uint32 GP2Y0A_Right = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->gp2y0a_right());
  }

  if (has_sen1()) {
    // required uint32 SEN1 = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->sen1());
  }

  if (has_hall_left_total()) {
    // required int32 Hall_Left_Total = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->hall_left_total());
  }

  if (has_motionst()) {
    // required uint32 MotionSt = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->motionst());
  }

  if (has_motiones()) {
    // required uint32 MotionEs = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->motiones());
  }

  if (has_pose_x()) {
    // required float pose_x = 8;
    total_size += 1 + 4;
  }

  if (has_pose_y()) {
    // required float pose_y = 9;
    total_size += 1 + 4;
  }

  if (has_pose_theta()) {
    // required float pose_theta = 10;
    total_size += 1 + 4;
  }

  return total_size;
}
int ToClient::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:test.ToClient)
  int total_size = 0;

  if (((_has_bits_[0] & 0x000003ff) ^ 0x000003ff) == 0) {  // All required fields are present.
    // required .test.ToClient.Type DataType = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->datatype());

    // required uint32 GP2Y0A_Left = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->gp2y0a_left());

    // required uint32 GP2Y0A_Right = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->gp2y0a_right());

    // required uint32 SEN1 = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->sen1());

    // required int32 Hall_Left_Total = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->hall_left_total());

    // required uint32 MotionSt = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->motionst());

    // required uint32 MotionEs = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->motiones());

    // required float pose_x = 8;
    total_size += 1 + 4;

    // required float pose_y = 9;
    total_size += 1 + 4;

    // required float pose_theta = 10;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional uint32 Image_Length = 11;
  if (has_image_length()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->image_length());
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ToClient::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:test.ToClient)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ToClient* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ToClient>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:test.ToClient)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:test.ToClient)
    MergeFrom(*source);
  }
}

void ToClient::MergeFrom(const ToClient& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:test.ToClient)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_datatype()) {
      set_datatype(from.datatype());
    }
    if (from.has_gp2y0a_left()) {
      set_gp2y0a_left(from.gp2y0a_left());
    }
    if (from.has_gp2y0a_right()) {
      set_gp2y0a_right(from.gp2y0a_right());
    }
    if (from.has_sen1()) {
      set_sen1(from.sen1());
    }
    if (from.has_hall_left_total()) {
      set_hall_left_total(from.hall_left_total());
    }
    if (from.has_motionst()) {
      set_motionst(from.motionst());
    }
    if (from.has_motiones()) {
      set_motiones(from.motiones());
    }
    if (from.has_pose_x()) {
      set_pose_x(from.pose_x());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_pose_y()) {
      set_pose_y(from.pose_y());
    }
    if (from.has_pose_theta()) {
      set_pose_theta(from.pose_theta());
    }
    if (from.has_image_length()) {
      set_image_length(from.image_length());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void ToClient::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:test.ToClient)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ToClient::CopyFrom(const ToClient& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:test.ToClient)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ToClient::IsInitialized() const {
  if ((_has_bits_[0] & 0x000003ff) != 0x000003ff) return false;

  return true;
}

void ToClient::Swap(ToClient* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ToClient::InternalSwap(ToClient* other) {
  std::swap(datatype_, other->datatype_);
  std::swap(gp2y0a_left_, other->gp2y0a_left_);
  std::swap(gp2y0a_right_, other->gp2y0a_right_);
  std::swap(sen1_, other->sen1_);
  std::swap(hall_left_total_, other->hall_left_total_);
  std::swap(motionst_, other->motionst_);
  std::swap(motiones_, other->motiones_);
  std::swap(pose_x_, other->pose_x_);
  std::swap(pose_y_, other->pose_y_);
  std::swap(pose_theta_, other->pose_theta_);
  std::swap(image_length_, other->image_length_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ToClient::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ToClient_descriptor_;
  metadata.reflection = ToClient_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ToClient

// required .test.ToClient.Type DataType = 1;
bool ToClient::has_datatype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ToClient::set_has_datatype() {
  _has_bits_[0] |= 0x00000001u;
}
void ToClient::clear_has_datatype() {
  _has_bits_[0] &= ~0x00000001u;
}
void ToClient::clear_datatype() {
  datatype_ = 0;
  clear_has_datatype();
}
 ::test::ToClient_Type ToClient::datatype() const {
  // @@protoc_insertion_point(field_get:test.ToClient.DataType)
  return static_cast< ::test::ToClient_Type >(datatype_);
}
 void ToClient::set_datatype(::test::ToClient_Type value) {
  assert(::test::ToClient_Type_IsValid(value));
  set_has_datatype();
  datatype_ = value;
  // @@protoc_insertion_point(field_set:test.ToClient.DataType)
}

// required uint32 GP2Y0A_Left = 2;
bool ToClient::has_gp2y0a_left() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void ToClient::set_has_gp2y0a_left() {
  _has_bits_[0] |= 0x00000002u;
}
void ToClient::clear_has_gp2y0a_left() {
  _has_bits_[0] &= ~0x00000002u;
}
void ToClient::clear_gp2y0a_left() {
  gp2y0a_left_ = 0u;
  clear_has_gp2y0a_left();
}
 ::google::protobuf::uint32 ToClient::gp2y0a_left() const {
  // @@protoc_insertion_point(field_get:test.ToClient.GP2Y0A_Left)
  return gp2y0a_left_;
}
 void ToClient::set_gp2y0a_left(::google::protobuf::uint32 value) {
  set_has_gp2y0a_left();
  gp2y0a_left_ = value;
  // @@protoc_insertion_point(field_set:test.ToClient.GP2Y0A_Left)
}

// required uint32 GP2Y0A_Right = 3;
bool ToClient::has_gp2y0a_right() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void ToClient::set_has_gp2y0a_right() {
  _has_bits_[0] |= 0x00000004u;
}
void ToClient::clear_has_gp2y0a_right() {
  _has_bits_[0] &= ~0x00000004u;
}
void ToClient::clear_gp2y0a_right() {
  gp2y0a_right_ = 0u;
  clear_has_gp2y0a_right();
}
 ::google::protobuf::uint32 ToClient::gp2y0a_right() const {
  // @@protoc_insertion_point(field_get:test.ToClient.GP2Y0A_Right)
  return gp2y0a_right_;
}
 void ToClient::set_gp2y0a_right(::google::protobuf::uint32 value) {
  set_has_gp2y0a_right();
  gp2y0a_right_ = value;
  // @@protoc_insertion_point(field_set:test.ToClient.GP2Y0A_Right)
}

// required uint32 SEN1 = 4;
bool ToClient::has_sen1() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void ToClient::set_has_sen1() {
  _has_bits_[0] |= 0x00000008u;
}
void ToClient::clear_has_sen1() {
  _has_bits_[0] &= ~0x00000008u;
}
void ToClient::clear_sen1() {
  sen1_ = 0u;
  clear_has_sen1();
}
 ::google::protobuf::uint32 ToClient::sen1() const {
  // @@protoc_insertion_point(field_get:test.ToClient.SEN1)
  return sen1_;
}
 void ToClient::set_sen1(::google::protobuf::uint32 value) {
  set_has_sen1();
  sen1_ = value;
  // @@protoc_insertion_point(field_set:test.ToClient.SEN1)
}

// required int32 Hall_Left_Total = 5;
bool ToClient::has_hall_left_total() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void ToClient::set_has_hall_left_total() {
  _has_bits_[0] |= 0x00000010u;
}
void ToClient::clear_has_hall_left_total() {
  _has_bits_[0] &= ~0x00000010u;
}
void ToClient::clear_hall_left_total() {
  hall_left_total_ = 0;
  clear_has_hall_left_total();
}
 ::google::protobuf::int32 ToClient::hall_left_total() const {
  // @@protoc_insertion_point(field_get:test.ToClient.Hall_Left_Total)
  return hall_left_total_;
}
 void ToClient::set_hall_left_total(::google::protobuf::int32 value) {
  set_has_hall_left_total();
  hall_left_total_ = value;
  // @@protoc_insertion_point(field_set:test.ToClient.Hall_Left_Total)
}

// required uint32 MotionSt = 6;
bool ToClient::has_motionst() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void ToClient::set_has_motionst() {
  _has_bits_[0] |= 0x00000020u;
}
void ToClient::clear_has_motionst() {
  _has_bits_[0] &= ~0x00000020u;
}
void ToClient::clear_motionst() {
  motionst_ = 0u;
  clear_has_motionst();
}
 ::google::protobuf::uint32 ToClient::motionst() const {
  // @@protoc_insertion_point(field_get:test.ToClient.MotionSt)
  return motionst_;
}
 void ToClient::set_motionst(::google::protobuf::uint32 value) {
  set_has_motionst();
  motionst_ = value;
  // @@protoc_insertion_point(field_set:test.ToClient.MotionSt)
}

// required uint32 MotionEs = 7;
bool ToClient::has_motiones() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void ToClient::set_has_motiones() {
  _has_bits_[0] |= 0x00000040u;
}
void ToClient::clear_has_motiones() {
  _has_bits_[0] &= ~0x00000040u;
}
void ToClient::clear_motiones() {
  motiones_ = 0u;
  clear_has_motiones();
}
 ::google::protobuf::uint32 ToClient::motiones() const {
  // @@protoc_insertion_point(field_get:test.ToClient.MotionEs)
  return motiones_;
}
 void ToClient::set_motiones(::google::protobuf::uint32 value) {
  set_has_motiones();
  motiones_ = value;
  // @@protoc_insertion_point(field_set:test.ToClient.MotionEs)
}

// required float pose_x = 8;
bool ToClient::has_pose_x() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void ToClient::set_has_pose_x() {
  _has_bits_[0] |= 0x00000080u;
}
void ToClient::clear_has_pose_x() {
  _has_bits_[0] &= ~0x00000080u;
}
void ToClient::clear_pose_x() {
  pose_x_ = 0;
  clear_has_pose_x();
}
 float ToClient::pose_x() const {
  // @@protoc_insertion_point(field_get:test.ToClient.pose_x)
  return pose_x_;
}
 void ToClient::set_pose_x(float value) {
  set_has_pose_x();
  pose_x_ = value;
  // @@protoc_insertion_point(field_set:test.ToClient.pose_x)
}

// required float pose_y = 9;
bool ToClient::has_pose_y() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
void ToClient::set_has_pose_y() {
  _has_bits_[0] |= 0x00000100u;
}
void ToClient::clear_has_pose_y() {
  _has_bits_[0] &= ~0x00000100u;
}
void ToClient::clear_pose_y() {
  pose_y_ = 0;
  clear_has_pose_y();
}
 float ToClient::pose_y() const {
  // @@protoc_insertion_point(field_get:test.ToClient.pose_y)
  return pose_y_;
}
 void ToClient::set_pose_y(float value) {
  set_has_pose_y();
  pose_y_ = value;
  // @@protoc_insertion_point(field_set:test.ToClient.pose_y)
}

// required float pose_theta = 10;
bool ToClient::has_pose_theta() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
void ToClient::set_has_pose_theta() {
  _has_bits_[0] |= 0x00000200u;
}
void ToClient::clear_has_pose_theta() {
  _has_bits_[0] &= ~0x00000200u;
}
void ToClient::clear_pose_theta() {
  pose_theta_ = 0;
  clear_has_pose_theta();
}
 float ToClient::pose_theta() const {
  // @@protoc_insertion_point(field_get:test.ToClient.pose_theta)
  return pose_theta_;
}
 void ToClient::set_pose_theta(float value) {
  set_has_pose_theta();
  pose_theta_ = value;
  // @@protoc_insertion_point(field_set:test.ToClient.pose_theta)
}

// optional uint32 Image_Length = 11;
bool ToClient::has_image_length() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
void ToClient::set_has_image_length() {
  _has_bits_[0] |= 0x00000400u;
}
void ToClient::clear_has_image_length() {
  _has_bits_[0] &= ~0x00000400u;
}
void ToClient::clear_image_length() {
  image_length_ = 0u;
  clear_has_image_length();
}
 ::google::protobuf::uint32 ToClient::image_length() const {
  // @@protoc_insertion_point(field_get:test.ToClient.Image_Length)
  return image_length_;
}
 void ToClient::set_image_length(::google::protobuf::uint32 value) {
  set_has_image_length();
  image_length_ = value;
  // @@protoc_insertion_point(field_set:test.ToClient.Image_Length)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace test

// @@protoc_insertion_point(global_scope)
